### ISSUE TITLE
Creación de VPS y BBDD

### ISSUE THREAD

**Issue by Mohamed11302** [Mohamed11302/MineriaDeDatosYSistemasMultiagentes#5]
Creación de la base de datos SQL para el almacenamiento de los Datasets. Esta base de datos estará alojada en un servidor VPS

**Comment by PabloDelHoyo** [comment]
Se ha contratado un VPS en la plataforma de hosting IONOS. Además, se ha decidido alquilar el nombre de dominio programadormanchego.es con la misma empresa.

En el VPS, se ha creado un contenedor de Docker que contiene una imagen de la base de datos MySQL 8.0. Para evitar que los datos guardados se pierdan cuando se elimina el contenedor, se ha optado por montar el tipo de volumen que la documentacion oficial de Docker recomienda en la ruta donde MySQL guarda los datos dentro del contenedor.

Además, se han modificado los registros DNS asociados al dominio mencionado anteriormente para hacer que el subdominio
db.programadormanchego.es sea un CNAME de programadormanchego.es. De esta manera, si en algún punto consideramos que necesitamos un servidor dedicado exclusivamente a la base de datos, no hará falta cambiar el host en el código de los programas
que se conectan a la misma.
