### ISSUE TITLE
[SILVER] Limpieza y transformación de datasets

### ISSUE THREAD

**Issue by Mohamed11302** [Mohamed11302/MineriaDeDatosYSistemasMultiagentes#8]
Limpieza y transformación de los datasets.
Se debe descargar de la base de datos tu dataset
Crear un método llamado limpieza_dataframe donde se limpien según el criterio seguido por cada dataframe

**Comment by EnriqueAP6** [comment]
Realizado

**Comment by luciaancos** [comment]
Finalizado

**Comment by Mohamed11302** [comment]
Terminado por parte de todos
