### ISSUE TITLE
Creación Tarjetas de Datos

### ISSUE THREAD

**Issue by Mohamed11302** [Mohamed11302/MineriaDeDatosYSistemasMultiagentes#9]
Creación de una tarjeta de datos por cada hipótesis.
Diego: hipótesis 1
Lucia: hipótesis 2 
Pablo: hipótesis 3
Enrique: hipótesis 4

**Comment by EnriqueAP6** [comment]
Realizado

**Comment by luciaancos** [comment]
Finalizado

**Comment by Mohamed11302** [comment]
Todos han terminado
